lab2 done
DekronPrime/ClientServerLabs pull request #2
Opened 2023-09-11 09:29 UTC by DekronPrime

2023-09-12 13:11 UTC, RuslanSlobodian requested changes

2023-09-12 13:11 UTC, RuslanSlobodian commented on Lab2/src/main/java/com/example/Abiturient.java
> +    public static void main(String[] args) {
Для чого зберігати метод main у коміті?

2023-09-12 13:11 UTC, RuslanSlobodian commented on Lab2/src/main/java/org/example/Menu.java
> +    public static int showMenu() {
Чому метод окрім відображення меню ще щось робить, це не випливає з назви методу

2023-09-12 13:11 UTC, RuslanSlobodian commented on Lab2/src/main/java/org/example/Main.java
> +            Scanner scanner = new Scanner(System.in);
Чому на кожній ітерації циклу потрібно створювати об'єкт класу Scanner?

2023-09-12 13:11 UTC, RuslanSlobodian commented on Lab2/src/main/java/org/example/Main.java
> +                        n = scanner.nextInt();
fix it

2023-09-12 13:11 UTC, RuslanSlobodian commented on Lab2/src/main/java/org/example/Main.java
> +    private static void sortArrayByAveragePointDesc(Abiturient[] abiturients) {
Для чого сортуєш вихідний масив?

2023-09-12 13:13 UTC, DekronPrime commented on Lab2/src/main/java/org/example/Menu.java
> +    public static int showMenu() {
Ок. Виправлю

2023-09-12 13:13 UTC, DekronPrime commented on Lab2/src/main/java/org/example/Main.java
> +            Scanner scanner = new Scanner(System.in);
Згоден, не логічно

2023-09-27 04:02 UTC, RuslanSlobodian requested changes

2023-09-27 04:02 UTC, RuslanSlobodian commented on Lab2/src/main/java/org/example/Main.java
> +        for (int i = 0; i < sortedAbiturientsArray.length - 1; i++) {
Це сортування масиву виправиш на одній з наступних робіт, а поки що ОК

2023-10-06 17:34 UTC, DekronPrime commented on Lab2/src/main/java/org/example/Main.java
> +        for (int i = 0; i < sortedAbiturientsArray.length - 1; i++) {
Добре

2023-10-06 17:35 UTC, DekronPrime commented on Lab2/src/main/java/org/example/Main.java
> +                            throw new Exception("Number n is out of range (0 > n < 6)");
Зрозумів. Якби і потрібно було б написати try - catch, то на рівень вище. Але в даному випадку, згоден: ця конструкція не доречна

2023-10-30 13:17 UTC, RuslanSlobodian approved these changes

2023-10-30 13:17 UTC, merged